spring:
  application:
    name: 'post-service'
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DB}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    restart:
      enabled: true
server:
  port: 8080
  error:
    include-message: always
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
      use-default-aws-credentials-chain: true
    region:
      static: ${AWS_REGION}
      auto: false
      use-default-aws-region-chain: true
    stack:
      auto: false
    endpoint-url: ${AWS_ENDPOINT_URL}
    s3-bucket: ${AWS_BUCKET_NAME}
logging:
  level:
    com.amazonaws.util.EC2MetadataUtils: error
    com.amazonaws.internal.InstanceMetadataServiceResourceFetcher: error
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
